version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    working_dir: "/api"
    volumes:
      - "./:/api"
    tty: true
    env_file:
      - './.env'
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    links:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: cliphype
      POSTGRES_PASSWORD: cliphype
      POSTGRES_DB: cliphype
    ports:
      - 5432:5432

